# Generated by Django 4.1 on 2022-09-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_experiment_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Procedure',
        ),
    ]
