# Generated by Django 4.1 on 2022-09-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_delete_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('step_image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(max_length=1000)),
                ('experiment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.experiment')),
            ],
        ),
    ]
