# Generated by Django 4.1 on 2022-09-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_rename_experiment_name_materialslist_experiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='step_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
